using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;

namespace Content.Client.UserInterface
{
    [GenerateTypedNameReferences]
    public partial class HUD : Control
    {
        public TextureRect TileAccessible => Tile;
    }
}

