using System;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.UserInterface
{
    [GenerateTypedNameReferences]
    public partial class MessageDialog : Control, IModal
    {
        public event EventHandler OnModalClosed;
        public MessageDialog(string text)
        {
            RobustXamlLoader.Load(this);
            Label.Text = text;
            OkButton.OnPressed += (a) => { Parent.RemoveChild(this); OnModalClosed.Invoke(this, new EventArgs()); };
        }
    }
}

